### ISSUE TITLE
Where is Decrypt Tool?

### ISSUE THREAD

**Issue by ghost** [ReddyyZ/DeathRansom#4]
Hello bro, the ransomware is awesome, but where is the Decryption tool?

**Comment by ReddyyZ** [comment]
Sorry me, I was too busy, now I'm going to develop the tool to decrypt

**Comment by ReddyyZ** [comment]
I'm already developing the decrypt script, I'm just fixing a bug and it's ready!

**Comment by ICTman1076** [comment]
Hurry up with it, you have literally just made malware creator's jobs a hell of a lot easier.

**Comment by ReddyyZ** [comment]
It's only for study.

**Comment by HamelinDiscord** [comment]
It's also open source, so now someone with bad intentions can literally just take your code and use it. You'd be mostly responsible for causing millions in damages. I wouldn't be surprised if the courts fined you for negligence.

**Comment by ICTman1076** [comment]
It's also open source, so now someone with bad intentions can literally just take your code and use it. While it wasn't you who spread it, you produced it, so you'd be mostly responsible for causing millions in damages. I wouldn't be surprised if the courts fined you for negligence.

**Comment by ReddyyZ** [comment]
A rifle maker is not punished for someone else killing someone using one.

**Comment by ICTman1076** [comment]
Rifles aren't malware. Rifles can be used for good purposes, so producing them is not an inherently bad thing. You've produced and supplied something that cannot do anything but harm. The only good use of this malware is when antimalware companies figure out how to block it.

**Comment by ReddyyZ** [comment]
Send me the article that punishes this then.

**Comment by ICTman1076** [comment]
Your country may vary, but [section 27 of the Computer Misuse Act 1990 prohibits the distribution of malware](https://en.wikipedia.org/wiki/Computer_Misuse_Act_1990#The_amendments). I imagine your country will have a similar law, but I'm not familiar with it. This is not legal advice, I am not a lawyer.

**Comment by ReddyyZ** [comment]
Ok, i will make this repository private.
