### ISSUE TITLE
Error unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by ittech25** [ReddyyZ/DeathRansom#5]
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\DeathRansom\time_script.py", line 22, in <module>
    restante = data-fday
TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Comment by ittech25** [comment]
Python 3.8.2 on Windows 10 - 32bit

**Comment by ReddyyZ** [comment]
Only the "Ransom Request" uses Python 3, the other scripts uses Python 2.

**Comment by ittech25** [comment]
Thank you @ReddyyZ . Problem resolved
